/**
 * @fileoverview gRPC-Web generated client stub for ilsp.spmd.asr
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: protos/asr.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ilsp = {};
proto.ilsp.spmd = {};
proto.ilsp.spmd.asr = require('./asr_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ilsp.spmd.asr.ILSPASRClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ilsp.spmd.asr.ILSPASRPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ilsp.spmd.asr.RecognizeRequest,
 *   !proto.ilsp.spmd.asr.RecognizeResponse>}
 */
const methodDescriptor_ILSPASR_Recognize = new grpc.web.MethodDescriptor(
  '/ilsp.spmd.asr.ILSPASR/Recognize',
  grpc.web.MethodType.UNARY,
  proto.ilsp.spmd.asr.RecognizeRequest,
  proto.ilsp.spmd.asr.RecognizeResponse,
  /**
   * @param {!proto.ilsp.spmd.asr.RecognizeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ilsp.spmd.asr.RecognizeResponse.deserializeBinary
);


/**
 * @param {!proto.ilsp.spmd.asr.RecognizeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ilsp.spmd.asr.RecognizeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ilsp.spmd.asr.RecognizeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ilsp.spmd.asr.ILSPASRClient.prototype.recognize =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ilsp.spmd.asr.ILSPASR/Recognize',
      request,
      metadata || {},
      methodDescriptor_ILSPASR_Recognize,
      callback);
};


/**
 * @param {!proto.ilsp.spmd.asr.RecognizeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ilsp.spmd.asr.RecognizeResponse>}
 *     Promise that resolves to the response
 */
proto.ilsp.spmd.asr.ILSPASRPromiseClient.prototype.recognize =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ilsp.spmd.asr.ILSPASR/Recognize',
      request,
      metadata || {},
      methodDescriptor_ILSPASR_Recognize);
};


module.exports = proto.ilsp.spmd.asr;

